//TODO EXPORT AND USE HERE THE DEFAULT COLORS AND OTHER CONSTANTS

export const DEFAULT_PRIMARY_COLOR = '#252525';
export const DEFAULT_SECONDARY_COLOR = '#333333';
export const DEFAULT_ACTION_COLOR = '#008CBA';